### ISSUE TITLE
Take advantage of the autoloader

### ISSUE THREAD

**Issue by PurpleBooth** [kylerdanielster/copello#1]
In your BoardAssets you manually include other classes. You don't need to do this, you can take advantage of the autoloader built into composer if you follow the [PSR-0](http://www.php-fig.org/psr/psr-0/) or [PSR-4](http://www.php-fig.org/psr/psr-4/) standards. To get this to work you'll need to add a [namespace](https://secure.php.net/manual/en/language.namespaces.php) to your classes too.

https://github.com/kylerdanielster/copello/blob/master/src/AppBundle/BoardAssets/Board.php#L3

**Comment by kylerdanielster** [comment]
I am having a hard time understanding how namespacing and autoloading
works. I can see how it works, I think, but I am trying to get it to work
with the namespace I created for the BoardAssets but either I do not know
how to test to see if it is working properly or it is not working because I
am doing it wrong, haha. and believe me, its not for lack of reading and
trying. Please help!
